typedef struct node{
    int type;
    int value;
    int childcnt;
    char* id;
    struct node** child;
}Node;

#define CONST_INSTRUCTION_CHILD         1
#define CONST_INSTRUCTION               2
#define VARIABLE_INSTRUCTION_CHILD      3
#define VARIABLE_INSTRUCTION            4
#define PROCEDURE_HEADER                5
#define SUBPROGRAM                      6
#define PROCEDURE_INSTRUCTION           7
#define SENTENCE                        8
#define EXPRESSION                      9
#define ITEM                            10
#define FACTOR                          11
#define MULTIPLY_OPERATOR               12
#define FACTOR_SUFFIX                   13
#define ITEM_SUF                        14
#define PLUS_OPERATOR                   15
#define UNEMPTY_SENTENCE                16
#define EMPTY_SENTENCE                  17
#define MULTI_SENTENCE                  18
#define COMPOUND                        19
#define RELATION_OPERATOR               20
#define CONDITION                       21
#define CONDITIONAL                     22
#define WHILELOOP                       23
#define PROCEDURE_CALL                  24
#define READ_PARAMETER                  25
#define READ_SENTENCE                   26
#define WRITE_SENTENCE                  27
#define WRITE_PARAMETER                 28
#define ASSIGNMENT                      29
#define PROGRAM                         30
#define FORLOOP                         31
#define LEFTPARAN                       32
#define RIGHTPARAN                      33
#define CONST_KEY                       34
#define VAR_KEY                         35
#define SEMI_OP                         36
#define PROCEDURE_KEY                   37
#define PROCEDURE_NAME                  38
#define BEGIN_KEY                       39
#define END_KEY                         40
#define IF_KEY                          41
#define THEN_KEY                        42
#define IDENTI                          43
#define NUMBER                          44
#define ASSIGN_OP                       45
#define WHILE_KEY                       46
#define DO_KEY                          47
#define FOR_KEY                         48
#define TO_KEY                          49
#define CALL_KEY                        50
#define READ_KEY                        51
#define WRITE_KEY                       52
#define CONST_DECLARATION               53
#define EQ_OP                           54
#define COMMA_OP                        55
#define VARIABLE_INSTRUCTIONSUF         56
#define ODD_KEY                         57
#define UEQ_OP                          58
#define LE_OP                           59
#define GE_OP                           60
#define GEQ_OP                          61
#define LEQ_OP                          62
#define PLUS_OP                         63
#define MINUS_OP                        64
#define MUL_OP                          65
#define DIV_OP                          66
#define EOP_OP                          67